services:
  backend:
    container_name: 
    build:
      context: 
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    
    fronted:
      container_name:
      build:
        context:
        dockerfile:
      ports:
      - "8501:8501"
      environment:
        BACKEND_URL: http://backend:8000